---
#--------------------------------------------------------------#
# 1. Pre-checks                                 [node_prechecks]
#--------------------------------------------------------------#
- import_tasks: prechecks.yml

#--------------------------------------------------------------#
# 2. Firewall                                    [node_firewall]
#--------------------------------------------------------------#
- import_tasks: firewall.yml

#--------------------------------------------------------------#
# 3. Packages                               [node_repo,node_pkg]
#--------------------------------------------------------------#
- import_tasks: pkg.yml

#--------------------------------------------------------------#
# 4. ADMIN    [node_profile, node_ulimit, node_data, node_admin]
#--------------------------------------------------------------#
- import_tasks: admin.yml

#--------------------------------------------------------------#
# 5. TIME                   [node_timezone, node_ntp, node_cron]
#--------------------------------------------------------------#
- import_tasks: time.yml
