# Basic settings
postgresql_version: 15
postgresql_encoding: "UTF-8"
postgresql_locale: "C.UTF-8"
postgresql_ctype: "C.UTF-8"
postgresql_admin_user: "postgres"
postgresql_default_auth_method: "peer"
postgresql_cluster_name: main
postgresql_cluster_reset: false

# List of databases to be created (optional)
postgresql_databases:
  - name: foobar
    owner: baz
    encoding: "UTF-8"
    state: "present"
    lc_collate: "en_GB.UTF-8"
    lc_ctype: "en_GB.UTF-8"
    hstore: yes
    uuid_ossp: yes
    citext: yes

# List of database extensions to be created (optional)
postgresql_database_extensions:
  - db: foobar
    extensions:
      - hstore
      - citex

# List of users to be created (optional)
postgresql_users:
  - name: baz
    pass: pass
    encrypted: yes
    state: "present"

# List of schemas to be created (optional)
postgresql_database_schemas:
  - database: foobar
    schema: acme
    state: presen
  - database: foobar
    schema: acme_baz
    owner: baz
    state: presen

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: baz
    db: foobar
    priv: "ALL"
    role_attr_flags: "CREATEDB"
