---
#---------------------------------------------------------------
# postgresql config                                  [pg-config]
#---------------------------------------------------------------
- name: PostgreSQL Config | Get Information
  become: yes
  become_user: "{{ postgresql_service_user }}"
  community.postgresql.postgresql_info:
  register: pg_info
- debug:
    msg:
      - "{{ pg_info['settings']['hba_file']['setting'] }}"

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ pg_info['settings']['hba_file']['setting'] }}"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries | length > 0
...
