---
#--------------------------------------------------------------#
# Install node repo (public or local)                [node_repo]
#--------------------------------------------------------------#
# Install Epel Repository
- name: Get epel-release-latest rpm package
  ansible.builtin.get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: /tmp/
    timeout: 30
    validate_certs: false
  when: install_epel_repo|bool
  tags: install_epel_repo

- name: Install EPEL repository
  ansible.builtin.package:
    name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  when: install_epel_repo|bool
  tags: install_epel_repo

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

#--------------------------------------------------------------#
# Install packages                                    [node_pkg]
#--------------------------------------------------------------#
- name: install node packages
  tags: node_pkg
  block:
    - name: supress deb auto start with policy-rc.d
      copy: src=policy-rc.d dest=/usr/sbin/policy-rc.d mode=0755
      when: os_package == 'deb'

    - name: install default node packages
      environment: "{{ proxy_env | default({}) }}"
      package: name={{ item }}
      with_items: "{{ node_default_packages }}"

    - name: install extra node packages
      environment: "{{ proxy_env | default({}) }}"
      package: name={{ item }}
      with_items: "{{ node_packages }}"
