---
#--------------------------------------------------------------#
# Pre-checks                                    [node_prechecks]
#--------------------------------------------------------------#
# This behaviour may be changed in the future
# It's acceptable to use this in isolated network environment
- name: node pre-checks
  tags: node_prechecks
  ignore_errors: false
  block:

    - name: Checking ansible version
      ansible.builtin.fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      delegate_to: localhost
      when:
        - ansible_version.full is version(minimal_ansible_version, '<')

    - name: Checking Linux distribution
      ansible.builtin.fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions

    - name: Checking version of OS Linux
      ansible.builtin.fail:
        msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
      when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')
...
