- name: restart postgresql
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: "{{ postgresql_daemon[ansible_pkg_mgr] }}"

- name: reload postgresql
  service:
    name: "{{ item }}"
    state: reloaded
    enabled: yes
  with_items: "{{ postgresql_daemon[ansible_pkg_mgr] }}"

- name: reload or restart postgresql service
  service:
    name: "{{ item }}"
    state: "{{ foo_state | default('reloaded') }}"
    enabled: yes
  with_items: "{{ postgresql_daemon[ansible_pkg_mgr] }}"
