---
- name: restart postgresql
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: "{{ postgresql_daemon[ansible_pkg_mgr] }}"

- name: reload postgresql
  service:
    name: "{{ item }}"
    state: reloaded
    enabled: yes
  with_items: "{{ postgresql_daemon[ansible_pkg_mgr] }}"
